spring.application.name=fleet-flow-backend



spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_flow
spring.datasource.username=postgres
spring.datasource.password=argusadmin
spring.jpa.hibernate.ddl-auto=update
server.port=9090